### ISSUE TITLE
General fixes/feedback

### ISSUE THREAD

**Issue by dispatchrabbi** [dispatchrabbi/half-day-security-guide#44]
My dad took a look and offered feedback. This is the easy/general stuff - there are a few other things that I'll put in other issues. I'm also going to use this issue to clean up a few parts of the text I found on a read-through.

### My dad's feedback

Introduction
- “straightforward” used twice.

Keep different parts of your life separate
- Formatting: hanging period after first sentence.
- sp. “acknowledgment” not “acknowledgement”

Pick services that are focused on one thing
- “…there’s less of a chance that the service will go away without warning.” Citation needed!!
  - Note from Eli: I don't know if there's a citation here that we can use, so maybe we change this so that it's clear that it's our opinion.)

Two-Factor Authentication
- “…we recommend using an authenticator app over text messages…” Not enough info here explaining what an authenticator app does as opposed to the text message approach – how does it look to the user? How does one set it up with a site that offers text TFA?, etc.

Internet of Things (IoT)
- Recommend adding home security systems and doorbell viewers to the list of examples.

Check the URL before Entering Sensitive Information
- Paranoia Alert!: I had to read the “Bonus Points…” sentence four times before I could decode it.  Suggest replacing “as” with “since” or “because”.

**Comment by cajunluke** [comment]
Apparently “acknowledgement” is en-uk and "acknowledgment" is en-us

**Comment by cajunluke** [comment]
re:
>“…there’s less of a chance that the service will go away without warning.” Citation needed!!

I think the citation is "you'll get warning because the service stops working because the company went away"
