### ISSUE TITLE
Add diagram for Three Dumb Routers

### ISSUE THREAD

**Issue by dispatchrabbi** [dispatchrabbi/half-day-security-guide#45]
Feedback from my dad:

> Internet of Things (IoT)
> - Three Dumb Routers: a simple block diagram might be helpful here Simple diagrams might be helpful in several other places: SSO, 2FA, DNS, VPN.

I think a diagram for 3DR would really be helpful as well. I don't know so much about SSO or the others, but he seemed to feel strongly about them. Still, 3DR does need it.

**Comment by cajunluke** [comment]
I was hoping the 3dr links handled that, but he may have seen an earlier version. Assign this to me, I have omnigraffle.

Bex Fortin

My pronouns are they/them

**Comment by dispatchrabbi** [comment]
All yours. I figured we'd do something with Mermaid but if you can do a better diagram in Omnigraffle, have at!
