### ISSUE TITLE
Make things look pretty

### ISSUE THREAD

**Issue by dispatchrabbi** [dispatchrabbi/half-day-security-guide#9]
The current site is... shall we say, drab. Here's what I'd like to see:

- Header up top with the title and subtitle
- The main content in the middle of the page, nicely formatted
- The table of contents on the left, with all headings visible to the user
- ~As the user scrolls the page, the current section is highlighted in the TOC~ (split to #16)
- ~Footnotes don't suck~ (split to #15)
- Move the license and "last updated" date to the footer (or its own section at the very end?)
- ~The page looks nice - probably going to want to find a nice typography CSS and a font or two. Maybe consult Amy on this?~ (split to #17)

Blocked by #3. Blocked by #8.

**Comment by dispatchrabbi** [comment]
This vision, obvs, is desktop-only. We can do mobile later.

**Comment by cajunluke** [comment]
(reopened as it's not done yet)
